name: Deploy to AWS
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for OIDC
      contents: read    # Required for actions/checkout
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: lokeshimpinge/aws-oidc-action@v1
        with:
          aws_region: us-east-1
          role_to_assume: ${{ secrets.AWS_OIDC_ROLE }}
      
      - name: Run AWS CLI command
        run: aws s3 ls
