name: AWS OIDC Connect Demo GA
on: push

permissions:
  id-token: write
  contents: read

jobs:
  simple_example:
    runs-on: ubuntu-latest
    name: Export AWS variables with a temporary session
    steps:
      - name: Fetch credentials
        uses: dflook/configure-oidc-aws-credentials@v1
        with:
          role-arn: arn:aws:iam::381491967540:role/github-action
          export-variables: true

      - name: Test credentials
        run: aws s3 ls

